<%@ Page Title="供应商管理" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="SupplierMaster.aspx.cs" Inherits="Admin_SupplierMaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<a href="CategoryMaster.aspx">分类管理</a>
<br />
<br />
<a href="SupplierMaster.aspx">供应商管理</a>
<br />
<br />
<a href="ProductMaster.aspx">商品管理</a>
<br />
<br />
<a href="OrderMaster.aspx">订单管理</a>
<br />
<br />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server"  TypeName="MyPetShop.BLL.SupplierService" DeleteMethod="DeleteSupplier" InsertMethod="InsertSupplier" SelectMethod="GetAllSuppliers" UpdateMethod="UpdateSupplier">
        <DeleteParameters>
            <asp:Parameter Name="suppId" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="suppId" Type="Int32" />
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="addr1" Type="String" />
            <asp:Parameter Name="addr2" Type="String" />
            <asp:Parameter Name="city" Type="String" />
            <asp:Parameter Name="state" Type="String" />
            <asp:Parameter Name="zip" Type="String" />
            <asp:Parameter Name="phone" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="suppId" Type="Int32" />
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="addr1" Type="String" />
            <asp:Parameter Name="addr2" Type="String" />
            <asp:Parameter Name="city" Type="String" />
            <asp:Parameter Name="state" Type="String" />
            <asp:Parameter Name="zip" Type="String" />
            <asp:Parameter Name="phone" Type="String" />
        </UpdateParameters>
    </asp:ObjectDataSource>
    <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateRows="False" DataKeyNames="SuppId" DataSourceID="ObjectDataSource1" OnItemDeleting="DetailsView1_ItemDeleting" AutoGenerateInsertButton="True">
        <Fields>
            <asp:BoundField DataField="SuppId" HeaderText="供应商ID" Visible="False" />
            <asp:BoundField DataField="Name" HeaderText="供应商名称" />
            <asp:BoundField DataField="Addr1" HeaderText="地址1" />
            <asp:BoundField DataField="Addr2" HeaderText="地址2" />
            <asp:BoundField DataField="City" HeaderText="城市" />
            <asp:BoundField DataField="State" HeaderText="区域" />
            <asp:BoundField DataField="Zip" HeaderText="邮编" />
            <asp:BoundField DataField="Phone" HeaderText="手机" />
        </Fields>
    </asp:DetailsView>
    <asp:Label ID="Label1" runat="server" ForeColor="Red"></asp:Label>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

